spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 2000ms
  datasource:
    url: jdbc:mysql://10.100.62.112:3306/reservation?autoReconnect=true&useAffectedRows=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    connection-timeout: 50000
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 3000
      maximum-pool-size: 20
      max-lifetime: 180000
      minimum-idle: 5